[workspace]
members = [
    "gcode-parser",
    # "gcode-validator",
    "gcode-interpreter",
    "pathviewer",
    "realtime-test",
    "streaming-gcode-parser"
]

[patch.crates-io]
gcode-parser = { path = "gcode-parser" }
gcode-interpreter = { path = "gcode-interpreter" }
streaming-gcode-parser = { path = "streaming-gcode-parser" }
